name = "liblsp_3_17"
description = "Language Server Protocol Support, Version 3.17"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0"
website = ""
tags = ["lsp"]

project-files = ["../gnat/lsp_3_17.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
liblsp_base = "*"

[[pins]]
liblsp_base = { path='../liblsp_base' }
