name = "langkit_support"
description = "Runtime support library for Langkit-generated libraries"
version = "24.0.0"

authors = ["AdaCore"]
maintainers = ["Pierre-Marie de Rodat <pmderodat@kawie.fr>", "chouteau@adacore.com"]
maintainers-logins = ["pmderodat", "Fabien-Chouteau"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = "https://github.com/AdaCore/langkit"

[environment]
GPR_PROJECT_PATH.prepend = "${CRATE_ROOT}/langkit/support"

[[depends-on]]
gnatcoll = "^24"
gnatcoll_iconv = "^24"
gnatcoll_gmp = "^24"
adasat = "^24"
