name = "vss_text"
description = "A high level Unicode text processing library"

long-description = """
## Warning - Work in Progress

This crate is based on [`VSS`](https://github.com/AdaCore/VSS) (Virtual
String System). VSS has been split into two crates:

* [`vss_text`](https://alire.ada.dev/crates/vss_text) (this crate): a library
  for Unicode text processing.
* [`vss_extra`](https://alire.ada.dev/crates/vss_extra): libraries for handling
  JSON, Regexp, XML and other features based on `vss_text`.

Significant changes are planned in `vss_text` with the goal to make it a
high-quality, high-performance library suitable for a wide range of
applications.

The changes include the following (non-exhaustive list):

* API Changes
  * Introduce an immutable string type.
  * Repurpose the mutable `Virtual_String` type to a string builder type.
  * Possibly rename the root package `VSS` to a new more appropriate name. Alire crate,
    GPR project and repository names might change accordingly.
* (done) Drop the support of multiple internal encodings in favor of a single internal
  encoding (likely UTF-8) for improved performance.
"""

version = "25.0.0-dev"
tags = ["unicode", "string", "text"]

authors = ["AdaCore"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
licenses = "Apache-2.0"
website = "https://github.com/AdaCore/vss-text"

project-files = ["gnat/vss_text.gpr"]

[configuration]
generate_ada = false
generate_c = false

[configuration.variables]
Max_Supported_Integer_Size = {type = "Enum", values = ["128", "64"], default = "128"}

[build-switches]
"*".ada_version = "Ada2022"

[environment.'case(os)'.macos.DYLD_LIBRARY_PATH]
append = "${CRATE_ROOT}/.libs/release/relocatable"

[environment.'case(os)'.windows.PATH]
append = "${CRATE_ROOT}/.libs/release/relocatable"

