install:
 - choco install gnat-gpl
 - echo C:/Projects /Projects ntfs auto 1 1 >> c:\msys64\etc\fstab
 - C:\msys64\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/integration/appveyor/appveyor.sh install"

build_script:
 - C:\msys64\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/integration/appveyor/appveyor.sh build"

artifacts:
  - path: win32*.zip

cache:
  - C:\Users\appveyor\AppData\Local\Temp\1\chocolatey\gnat-gpl\2020.0 -> integration\appveyor\appveyor.sh
deploy:
  - provider: BinTray
    on:
      branch: master
    username: reznikmm
    api_key:
      secure: A1Zo2PTNbMuel5lJMl2ymTrMMTYyQm2bc3sp04HIW8A4Dw3AP9038+5/1RsoA/ZT
    subject: reznikmm
    repo: ada-language-server
    package: ada-language-server
    version: latest
    publish: true
    override: true
    explode: false
  - provider: BinTray
    on:
      APPVEYOR_REPO_TAG: true
    username: reznikmm
    api_key:
      secure: A1Zo2PTNbMuel5lJMl2ymTrMMTYyQm2bc3sp04HIW8A4Dw3AP9038+5/1RsoA/ZT
    subject: reznikmm
    repo: ada-language-server
    package: ada-language-server
    version: $(APPVEYOR_REPO_TAG_NAME)
    publish: true
    override: true
    explode: false
