stages:
  - build
  - test
  - optional
  - check

include:
  # Issue check
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/check-issue@~latest

  # Build
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/build@~latest
    inputs:
      anod-args: run build_$ACI_TRACK
      cpus: 16
      image: systemgtk
      save-component: true

  # Testing of the ALS
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/test@~latest
    inputs:
      job-name: als
      anod-args: run test_als_$ACI_TRACK
      image: systemgtk

  # Testing of the VSCode extension
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/test@~latest
    inputs:
      job-name: vscode-extension
      anod-args: run test_vscode_extension_$ACI_TRACK
      image: systemgtk

  # Integration testsuite
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/test@~latest
    inputs:
      job-name: integration-testsuite
      # Here we would like to use --latest as to reduce issues from unavailable
      # components, but we can't because it breaks the transfer of built
      # components between jobs using anod-copy-components.
      #
      # See https://gitlab.adacore-it.com/eng/ide/ada_language_server/-/merge_requests/1611#note_610445
      anod-args: run test_integration_testsuite
      image: systemgtk
      cpus: 4
      rules:
        # Does not work on edge
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_TARGET_BRANCH_NAME != 'edge'

  # Optional testing of GNAT Studio
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/test@~latest
    inputs:
      job-name: gs
      anod-args: run build_test_gs_$ACI_TRACK
      image: systemgtk
      stage: optional
      rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
          when: manual
          allow_failure: true
