os:
  - linux
  - osx

services:
  - docker

language: generic

before_install:
  - integration/travis/travis.sh before_install

script:
  - integration/travis/travis.sh script

deploy:
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH == master || $TRAVIS_TAG =~ ^[0-9.]+$
  skip_cleanup: true
  provider: bintray
  file: integration/travis/bintray.json
  user: reznikmm
  key:
    secure: "YXIjjteooikFPr+lsZ3+Rg/NjSmUI346yKte7wmOWDjcm8q/pp6YtdKj9jYz/sjoUQMc0HHJjlmWfAz7ZR1iH9doIGVmEcnkTqB63DAowBfvq0NIn0pjzwJ91Wu3k8BnDjMWBjwiOwqwsSj7tHRxrIMTQqtxMu8v8OWSLcBukIFxqyxNcnX1MCAXci9ePigBCB4sRUzVdXIMTsKSjk4JFHxKgAaavSxQnn326UsnKoiMw9SAO3uZfmKAMlofKxQO4q2cuERl4iYwiL+lAsbGoadZvXPH6ThKmMhoBdJRLPZNzFD8pOKEWS43/AiIaHeWIw6NEg2NsyiXE6b69/s44LwnSEckPFZBjIdiceOLTH7v5ZzDH/pNg2GmnzszHup6a+/ocCjA9pSltIEVRF0ZsX1KEQScWneJqRaTCT1+uBYmDturKy4hmcnNhBFx3pfpoCgdqz5HOxWGsln4zCpRrb0K+W/p445uWHUu7ze5XRzB7ylfHJbYrYLC9p+GKseYC6qkYt8q9wah8bUQxD8RFCdKJIt+jD3PvETjGAn0Q4cSXLsMOjtDuvRSzetAzAMs15+TzaMHIHnHn5P2uAvTucb0btfwP6nUIg7VEKT6MURxjW4bRjryriJmxYEFxaCU0pVfSuONYal8bXL8dxyoFHYP6dWbaCqURurzy8WxyJM="

jobs:
  include:
    - stage: deploy
      os: linux
      if: ( branch = master OR tag =~ /^[0-9.]+$/ ) AND type = push
      before_install: echo before_install
      script: integration/travis/deploy.sh vsix

env:
  global: # VSCE_TOKEN variable
    secure: "2UktUSXjy1zYT23x/MeEwhsFLoCowRbABN+A26RWjqJCbOnrR4BahQE+Jiyn3ofDq0pzzlyHmkxRAGhKuUhWXRXYAkkoqbBYbmDopbuWYS3yvI7m5GH52AxOzjl0GKuviuys2fo+vZl20cRI+vPPB8mPo4AF2VlK+fklNp2oYOUqGEvKi0kE/S2AB42xyERJ9PQzTo0ilQBqvDhxy1bmLmd3r+AcN/Gi0Ff7Qk2jm5AAlqOWT68jJPVmqx9MeP4iATzpJqdYqWBMr0ycS7LWWQE9z5Q8BG6PAQ5rRjL/ixjwS8qp5hrrYNXeEC46IbaI6CkPtwG1nQAjVwnJY3ySwj0KNTcGRZa2QlJzgD76eCAAYgvYUinoLvGMGJsWm2JFw4JPo6uDUSpGIuSI1g+g9kPJj83f8ey91jB+iAivkFC6z5N4PrNwfplzJptaAksNkJAipw9HZLEaqMBld63I/ibBnmpZ3sl+RaISnLk/yE19je8Uwm3CuiKWQsbtHm/c516EVMZ7U7oHNHwF7FJhlAmHJXR1ksj6Dek8hjBU1KQi37ZMdD6g/jcTzT/Dmz4DKzNMhhmZsKjhyW8sg0qZgj8D1bjkL/iyYeXyWn3DMcSoc1K5UN1tVne7esrxplltlaIQq4kdM9ddVorHUIXCIGSVcZCeEpRkhkgkIlmfoO8="
