os:
  - linux
  - osx

osx_image: xcode11.4

language: generic

before_install:
  - integration/travis/travis.sh before_install

script:
  - integration/travis/travis.sh script

cache:
  directories:
  - $HOME/cache

deploy:
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH == master || $TRAVIS_TAG =~ ^[0-9.]+$
  skip_cleanup: true
  provider: bintray
  file: integration/travis/bintray.json
  user: reznikmm
  key:
    secure: "YXIjjteooikFPr+lsZ3+Rg/NjSmUI346yKte7wmOWDjcm8q/pp6YtdKj9jYz/sjoUQMc0HHJjlmWfAz7ZR1iH9doIGVmEcnkTqB63DAowBfvq0NIn0pjzwJ91Wu3k8BnDjMWBjwiOwqwsSj7tHRxrIMTQqtxMu8v8OWSLcBukIFxqyxNcnX1MCAXci9ePigBCB4sRUzVdXIMTsKSjk4JFHxKgAaavSxQnn326UsnKoiMw9SAO3uZfmKAMlofKxQO4q2cuERl4iYwiL+lAsbGoadZvXPH6ThKmMhoBdJRLPZNzFD8pOKEWS43/AiIaHeWIw6NEg2NsyiXE6b69/s44LwnSEckPFZBjIdiceOLTH7v5ZzDH/pNg2GmnzszHup6a+/ocCjA9pSltIEVRF0ZsX1KEQScWneJqRaTCT1+uBYmDturKy4hmcnNhBFx3pfpoCgdqz5HOxWGsln4zCpRrb0K+W/p445uWHUu7ze5XRzB7ylfHJbYrYLC9p+GKseYC6qkYt8q9wah8bUQxD8RFCdKJIt+jD3PvETjGAn0Q4cSXLsMOjtDuvRSzetAzAMs15+TzaMHIHnHn5P2uAvTucb0btfwP6nUIg7VEKT6MURxjW4bRjryriJmxYEFxaCU0pVfSuONYal8bXL8dxyoFHYP6dWbaCqURurzy8WxyJM="

jobs:
  include:
    - stage: deploy
      os: linux
      if: ( branch = master OR tag =~ /^[0-9.]+$/ ) AND type = push
      before_install: echo before_install
      script: integration/travis/deploy.sh vsix

env:
  global: # VSCE_TOKEN variable
    secure: pZ5XFVHWfSd1ToUod4A5DYABec00dLMm83VzAAg7GNDSgeQwnhscH8hW94d3TpqMpnrDOiu1nH2KJvGcmdkikJkeF6wfTdpZUnSLj0MPliC6nKjmH/IkjEWUUdCfeSi6nD1Q8M6lMBlrCsCpX1RETFc8cW60j2hv0Ngc68pxtx+ZNOe8HyrPAVU7W3mE2ITimUMTgmNphQfXN2IhwGADULhXoe0hY3V9Ndj+tjlP+DPcDksoGT4MFk6/R3RSwAozYp4K+HWor1s1sa/JJcWtadBAmq7hoWl1uaoe/pnuLH9F0/0XOxNtjdff3d0Mn/8KzfqnWGOClJFTNJzzHODo3TSjgZ8lJQM6nbmK6InIXvLIAFqKWcr0sVi59quB9UWqNBtxmA1PkGc3TAJ6GdiljcVdL7MidFj9v72l04Dh+GXGu+F/QG01o+oyInSliYBsmG6bcvoEefBixhyglxUoYrS5Vnm1Pc3bnwGdiv7b3I9YHP65s2P1AnVKMdWsayU3S1uAnDe11KK7GjnRMnPZH85//+ZHE2F16Kqq7bip/j2R8CnOWX+v4er6johJ2oZZpMeh4kbRPmMV6futinp/1KbVlAmVPIogdFwkyXAB8NMXjmGH5DoB12QxirSmM025PGyZHcQT1aS/V7kVA5qgAsAG3rpgvrT4yPlSnyvXGxk=

