<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>comment</key>
  <string>Ada grammar file</string>
  <key>fileTypes</key>
  <array>
    <string>adb</string>
    <string>adc</string>
    <string>ads</string>
  </array>
  <key>name</key>
  <string>Ada</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>match</key>
      <string>--[^\n\r]*</string>
      <key>name</key>
      <string>comment.line.double-dash.ada</string>
    </dict>
    <dict>
      <key>match</key>
      <string>([0-9][0-9_]*(\.[0-9][0-9_]*)?)</string>
      <key>name</key>
      <string>constant.numeric.ada</string>
    </dict>
    <dict>
      <key>match</key>
      <string>'.'</string>
      <key>name</key>
      <string>constant.character.ada</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(?i:(null|true|false))\b</string>
      <key>name</key>
      <string>constant.lanuage.ada</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(?i:(aaa))\b</string>
      <key>name</key>
      <string>entity.name.function.ada</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(?i:(abort|delay|exit|goto|pragma|raise|requeue|terminate|until))\b</string>
      <key>name</key>
      <string>keyword.control.ada</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(?i:(abs|and|in|mod|not|of|or|rem|xor))\b</string>
      <key>name</key>
      <string>keyword.operator.ada</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(?i:(abstract|accept|access|aliased|all|array|at|begin|body|case|constant|declare|delta|digits|do|else|elsif|end|entry|exception|for|function|generic|if|interface|is|limited|loop|new|others|out|overriding|package|private|procedure|protected|range|record|renames|return|reverse|select|separate|some|subtype|synchronized|tagged|task|then|type|use|when|while|with))\b</string>
      <key>name</key>
      <string>keyword.other.ada</string>
    </dict>
    <dict>
      <key>match</key>
      <string>"([^"]|"")*"</string>
      <key>name</key>
      <string>string.quoted.double.ada</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(?i:(Boolean|Integer|Natural|Positive|Character|String))\b</string>
      <key>name</key>
      <string>support.type.ada</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(?i:(Ada|Text_IO|Strings))\b</string>
      <key>name</key>
      <string>support.function.ada</string>
    </dict>
  </array>
  <key>scopeName</key>
  <string>source.ada</string>
  <key>uuid</key>
  <string>4DDE765F-8597-4242-86C5-377654070343</string>
</dict>
</plist>
