#!/bin/bash
set -e
# A dummy Alire replacement for testing purposes

# Skip parameters starting with '-' until the Alire action is reached
while [ $# -gt 1 ] && [[ $1 == -* ]] ; do shift ; done

DIR=`cd $(dirname $0); pwd`
GNAT=$(dirname `which gnat`)
sed -e "s#\${DIR}#${DIR}#g" -e "s#\${GNAT}#${GNAT}#g" ${DIR}/.alr_$1
