name = "liblsp_base"
description = "Language Server Protocol Support, Base Package"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0"
website = ""
tags = ["lsp"]

project-files = ["../gnat/lsp_base.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
vss = "*"
