#!/bin/env python

# A mini utility that can generate a test driver from the data generated
# by a run of the ALS.
# To do this, activate the ALS.IN and ALS.OUT traces, and

# This takes as parameters:
#        - path to a file generated by the ALS.IN trace
#        - path to a file generated by the ALS.OUT trace
#        - the path of the root project on which the als ran
# and generates on the standard

import sys
import json
import json_transformations

print json.dumps(json_transformations.traces_to_test(
                    sys.argv[1], sys.argv[2], sys.argv[3]),
                 indent=3, sort_keys=True)
